sth = input('Digite algo: ')
print('O tipo primitivo é {}'.format(type(sth)))
print('Só tem espaços? ', sth.isspace())
print('É um número?', sth.isnumeric())
print('É alfabético?', sth.isalpha())
print('É alfanumérico?', sth.isalnum())
print('Está em maiúscula?', sth.isupper())
print('Está em minúsculas?', sth.islower())
print('Está capitalizada?', sth.istitle())
